ROW_HEADER = 'Row'
COLUMN_HEADER = 'Column'
COMPOUND_HEADER = 'Compound'
FIELD_HEADER = 'Field'
MEDIAN_HEADER = 'Median'
VARIATION_HEADER = 'Variation'
COORDINATES_COLUMNS = [ROW_HEADER, COLUMN_HEADER, FIELD_HEADER]
DMSO = 'DMSO'
